### ISSUE TITLE
Login not allowed on Brave browser

### ISSUE THREAD

**Issue by sam17** [nuwandavek/okru#4]
```
"This browser is not supported or 3rd party cookies and data may be disabled. "
```
On Brave Browser

**Comment by sam17** [comment]
Links describing the issue 
- https://github.com/brave/brave-browser/issues/7693
- https://github.com/firebase/quickstart-js/issues/419

**Comment by nuwandavek** [comment]
This is a firebase issue, looks like. Closing this for now.
