### ISSUE TITLE
When testing locally, sign-in is impossible

### ISSUE THREAD

**Issue by ppsreejith** [nuwandavek/okru#7]
On firebase/google-auth, redirect to domain localhost:3000 is not registered.

Related to this issue -> https://stackoverflow.com/questions/37603118/firebase-auth-onauthstatechanged-not-working

Thus we can't test locally as we can't sign in locally.

**Comment by nuwandavek** [comment]
This is strange, because I test locally while developing. It redirects to localhost:3000!

**Comment by ppsreejith** [comment]
Gotcha. Let me try something else and get back to you on this 👍

**Comment by nuwandavek** [comment]
Closing this issue.
